restaurant/reservations/urls.py
from django.urls import path
from . import views
from .views import (
    ReservationDeleteView, ReservationsListView, ReservationDetailView
)

app_name = 'reservations'

urlpatterns = [
    path('reservation', views.ReservationView, name='reservation'),
    path('reservationsList', ReservationsListView.as_view(), name='reservationsList'),
    path('reservationDetail/<int:pk>', ReservationDetailView.as_view(), name='reservationDetail'),
    path('reservationUpdate/<int:pk>', views.ReservationUpdateView, name='reservationUpdate'),
    path('reservationDelete/<int:pk>', ReservationDeleteView.as_view(), name='reservationDelete'),

    
]

restaurant/restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('reservations.urls')),
    path('users/', include('users.urls')),
]

restaurant/users/urls.py
from django.urls import path
from .views import AdminLogoutView, HomeView, AdminLoginView 

app_name = 'users'

urlpatterns = [
    path('home', HomeView.as_view(), name='home'),
    path('admin_login', AdminLoginView.as_view(), name='admin_login'),
    path('admin_logout', AdminLogoutView.as_view(), name='admin_logout')
]

restaurant/reservations/models.py
from django.db import models


class Reservations(models.Model):
    id = models.AutoField(primary_key=True)
    last_name = models.CharField(verbose_name='氏名（姓）', max_length=15)
    first_name = models.CharField(verbose_name='氏名（名）', max_length=15)
    reservation_date = models.DateTimeField(verbose_name='予約日時')
    reservation_count = models.IntegerField(verbose_name='予約人数')
    tell = models.CharField(verbose_name='電話番号', max_length=12)
    celebration_existence = models.IntegerField(verbose_name='お祝い有無')
    demand = models.TextField(verbose_name='要望',null=True, blank=True)
    created_at = models.DateTimeField(verbose_name='登録日時')
    update_at = models.DateTimeField(verbose_name='更新日時')

    class Meta:
        db_table = 'reservations'
    
    def __str__(self):
        return self.last_name + self.first_name

restaurant/reservations/forms.py
from django import forms
from datetime import date, timedelta, datetime
from .models import Reservations
from django.utils import timezone

# 2週間
TWO_WEEK = []
today = date.today()
for i in range(0, 13):
    TWO_WEEK.append((f'{today + timedelta(days=i)}', f'{today + timedelta(days=i)}'))

# 予約時間
TIME = [
    ('11:00:00', '11:00 ~ 13:00'),
    ('13:00:00', '13:00 ~ 15:00'),
    ('15:00:00', '15:00 ~ 17:00'),
    ('17:00:00', '17:00 ~ 19:00'),
    ('19:00:00', '19:00 ~ 21:00'),
    ('21:00:00', '21:00 ~ 23:00')
]

# 予約人数
COUNT = []
for i in range(1, 7):
    COUNT.append((f'{i}', f'{i}'))



# 予約登録、更新フォーム
class ReservationForm(forms.Form):
    last_name = forms.CharField(max_length=15)
    first_name = forms.CharField(max_length=15)
    reservation_day = forms.ChoiceField(choices=TWO_WEEK, widget=forms.widgets.Select)
    reservation_time = forms.ChoiceField(choices=TIME, widget=forms.widgets.Select)
    reservation_count = forms.ChoiceField(choices=COUNT, widget=forms.widgets.Select)
    tell = forms.CharField(max_length=12)
    celebration_existence = forms.BooleanField(required=False, initial=False, widget=forms.CheckboxInput())
    demand = forms.CharField(required=False, widget=forms.Textarea())

    # バリデーション
    def clean(self):
        messages = []
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        messages.append(validationNullCheck(first_name, '氏名（名）'))
        last_name = cleaned_data.get('last_name')
        messages.append(validationNullCheck(last_name, '氏名（姓）'))
        tell = cleaned_data.get('tell')
        messages.append(validationNullCheck(tell, '電話番号'))
        celebration_existence = cleaned_data.get('celebration_existence')
        demand = cleaned_data.get('demand')
        if celebration_existence == True and demand == '':
            messages.append(validationNullCheck(demand, '要望'))
        
        error_msg = []
        for message in messages:
            if message != None:
                error_msg.append(message)
        if len(error_msg) != 0:
            raise forms.ValidationError(error_msg)


def validationNullCheck(value, item):
    if value == None or len(value) == 0:
        return f'{item}を入力して下さい'

restaurant/reservations/views.py
from django.http import request
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from .models import Reservations
from .forms import ReservationForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    DeleteView
)
from datetime import datetime
import datetime as dt
from django.core.paginator import (
    Paginator, EmptyPage, PageNotAnInteger
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required



# 予約登録
def ReservationView(request):
    form = ReservationForm(request.POST or None)

    if form.is_valid():
        reservation = Reservations()
        # 氏名（姓）
        reservation.last_name = form.cleaned_data['last_name']
        # 氏名（名）
        reservation.first_name = form.cleaned_data['first_name']
        # 予約日時
        reservation.reservation_date = day_time_value(form.cleaned_data['reservation_day'], form.cleaned_data['reservation_time'])
        # 予約人数
        reservation.reservation_count = form.cleaned_data['reservation_count']
        # 電話番号
        reservation.tell = form.cleaned_data['tell']
        # お祝い
        if form.cleaned_data['celebration_existence']:
            reservation.celebration_existence = 1
        else:
            reservation.celebration_existence = 0
        # お店への要望
        reservation.demand = form.cleaned_data['demand']

        # 登録
        Reservations.objects.create(
            last_name = reservation.last_name,
            first_name = reservation.first_name,
            reservation_date = reservation.reservation_date,
            reservation_count = reservation.reservation_count,
            tell = reservation.tell,
            celebration_existence = reservation.celebration_existence,
            demand = reservation.demand,
            created_at = datetime.now(),
            update_at = datetime.now(),
        )
        return redirect('users:home')
    return render(request, 'store/reservation.html', {'form': form})
    
    

# 予約一覧
class ReservationsListView(LoginRequiredMixin,    ListView):
    model = Reservations
    template_name = 'store/reservationsList.html'
    # 5件ずつ
    paginate_by = 5

    # 検索機能
    def get_queryset(self):
        query = super().get_queryset()
        # 予約ID
        reservation_id = self.request.GET.get('id', None)
        # 氏名（姓）
        last_name = self.request.GET.get('last_name', None)
        # 氏名（名）
        first_name = self.request.GET.get('first_name', None)
        # 予約日時間（先）
        start_day_time = str(self.request.GET.get('start_day', None)) + ' ' + '00:00:00'
        # 予約日時間（後）
        end_day_time = str(self.request.GET.get('end_day', None)) + ' ' + '23:59:59'
        # 予約日（先）
        start_day = self.request.GET.get('start_day', None)
        # 予約日（後）
        end_day = self.request.GET.get('end_day', None)
        # 予約人数
        reservation_count = self.request.GET.get('reservation_count', None)
        # 電話番号
        tell = self.request.GET.get('tell', None)
        # 予約受付日
        created_at = self.request.GET.get('created_at', None)
        
        # 検索フィルター
        # ID
        if reservation_id:
            query = query.filter(
                id = reservation_id
            )

        # 氏名（姓）
        if first_name:
            query = query.filter(
                first_name__contains = first_name
            )

        # 氏名（名）
        if last_name:
            query = query.filter(
                last_name__contains = last_name
            )

        # 予約日時
        if start_day and end_day:
            query = query.filter(
                reservation_date__range = [start_day_time, end_day_time]
            ).order_by('reservation_date')
        elif start_day:
            query = query.filter(
                reservation_date__gte = start_day_time
            ).order_by('reservation_date')
        elif end_day:
            query = query.filter(
                reservation_date__lte = end_day_time
            ).order_by('reservation_date')

        # 予約人数
        if reservation_count:
            query = query.filter(
                reservation_count = reservation_count
            )

        # 電話番号
        if tell:
            query = query.filter(
                tell = tell
            )

        # 予約受付日
        if created_at:
            query = query.filter(
                created_at__contains = created_at
            )
        
        # ページネーション
        paginator = Paginator(query, self.paginate_by)
        page = self.request.GET.get('page')
        try:
            paginator.page(page)
        except PageNotAnInteger:
            paginator.page(1)
        except EmptyPage:
            paginator.page(paginator.num_pages)

        return query
    
    # template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ID
        context['id'] = self.request.GET.get('id', '')
        # 氏名（姓）
        context['last_name'] = self.request.GET.get('last_name', '')
        # 氏名（名）
        context['first_name'] = self.request.GET.get('first_name', '')
        # 予約日from
        context['start_day'] = self.request.GET.get('start_day', '')
        # 予約日to
        context['end_day'] = self.request.GET.get('end_day', '')
        # 予約人数
        context['reservation_count'] = self.request.GET.get('reservation_count', '')
        # 電話番号
        context['tell'] = self.request.GET.get('tell', '')
        # 予約受付日
        context['created_at'] = self.request.GET.get('created_at', '')
        return context



# 予約詳細
class ReservationDetailView(LoginRequiredMixin, DetailView):
    model = Reservations
    template_name = 'store/reservationDetail.html'

    # template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 予約日時
        context['time'] = time_view(self.object.reservation_date)
        # お祝い
        if self.object.celebration_existence == 0:
            context['celebration_existence'] = 'なし'
        elif self.object.celebration_existence == 1:
            context['celebration_existence'] = 'あり'

        return context



# 予約更新
@login_required
def ReservationUpdateView(request, pk):
    # 予約ID情報
    reservation_data = Reservations.objects.get(id=pk)
    # 初期表示
    if request.method == 'GET':
        # お祝い
        if reservation_data.celebration_existence == 1:
            reservation_data.celebration_existence = True
        else:
            reservation_data.celebration_existence = False
        # 予約日と予約時間
        day_time = reservation_data.reservation_date + dt.timedelta(hours=9)
        day = day_time.strftime('%Y-%m-%d')
        time = day_time.strftime('%H:%M:%S')

        item = {
            'last_name': reservation_data.last_name,
            'first_name': reservation_data.first_name,
            'reservation_day': day,
            'reservation_time': time,
            'reservation_count': reservation_data.reservation_count,
            'tell': reservation_data.tell,
            'celebration_existence': reservation_data.celebration_existence,
            'demand': reservation_data.demand
        }
        form = ReservationForm(initial=item)
    # 更新
    else:
        form = ReservationForm(request.POST or None)
        if form.is_valid():
            # 予約ID情報
            reservation = Reservations.objects.get(id=pk)
            # 氏名（姓）
            reservation.last_name = form.cleaned_data['last_name']
            # 氏名（姓）
            reservation.first_name = form.cleaned_data['first_name']
            # 予約日時
            reservation.reservation_date = day_time_value(form.cleaned_data['reservation_day'], form.cleaned_data['reservation_time'])
            # 予約人数
            reservation.reservation_count = form.cleaned_data['reservation_count']
            # 電話番号
            reservation.tell = form.cleaned_data['tell']
            # お祝い
            if form.cleaned_data['celebration_existence']:
                reservation.celebration_existence = 1
            else:
                reservation.celebration_existence = 0
            # お店への要望
            reservation.demand = form.cleaned_data['demand']
            # 保存
            reservation.save()
            return redirect('reservations:reservationDetail', pk=pk)
    return render(request, 'store/reservationUpdate.html', context = {
        'form': form,
        'reservation': reservation_data,
    })



# 予約削除
class ReservationDeleteView(LoginRequiredMixin, DeleteView):
    model = Reservations
    template_name = 'store/reservationDelete.html'
    success_url = reverse_lazy('reservations:reservationsList')
    # template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 予約日時
        context['time'] = time_view(self.object.reservation_date)
        # お祝い
        if self.object.celebration_existence == 0:
            context['celebration_existence'] = 'なし'
        elif self.object.celebration_existence == 1:
            context['celebration_existence'] = 'あり'

        return context







# ---------    メソッド    ---------


# 日と時間を足してdatetime型に変換
def day_time_value(day, time):
    day_time = day + ' ' + time
    day_time = datetime.strptime(day_time, '%Y-%m-%d %H:%M:%S')
    return day_time



# 時間の表示変換
def time_view(time):
    # プラス9時間
    time_nine = time + dt.timedelta(hours=9)
    # ％H：％Mに変換
    time_hm = str(time_nine.hour) + ':' + str(time_nine.minute) + '0'
    time_change = ''
    if time_hm == '11:00':
        time_change = str(time_hm) + ' ' + '~' + ' ' + '15:00'
    elif time_hm == '15:00':
        time_change = str(time_hm) + ' ' + '~' + ' ' + '17:00'
    elif time_hm == '17:00':
        time_change = str(time_hm) + ' ' + '~' + ' ' + '19:00'
    elif time_hm == '19:00':
        time_change = str(time_hm) + ' ' + '~' + ' ' + '21:00'
    elif time_hm == '21:00':

restaurant/templates/store/reservation.html
{% extends 'base.html' %}
{% block content %}
<h2>予約登録</h2>
<h2>■ご予約内容を入力してください。</h2>
<form method='POST' novalidate>
    {% csrf_token %}
    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            【{{ error }}】
        {% endfor %}
    {% endif %}
    <p>
        お名前 {{ form.last_name }} {{ form.first_name }}
    </p>
    <p>
        来店日時 {{ form.reservation_day}} {{ form.reservation_time }}
    </p>
    <p>
        来店人数 {{ form.reservation_count }}
    </p>
    <p>
        電話番号 {{ form.tell }}
    </p>
    <p>
        お祝い {{ form.celebration_existence }}
    </p>
    <p>
        お店への要望 {{ form.demand }}
    </P>
    <button>
        <a href="{% url 'users:home' %}">
        戻る
        </a>
    </button>
    <input type='submit' value='予約する'>
</form>
{% endblock %}

restaurant/templates/store/reservationDelete.html
{% extends 'base.html' %}
{% block content %}
<h2>予約削除確認</h2>
<p>下記予約を削除しますがよろしいでしょうか？</p>
<p>
    予約ID {{ object.id }}
</p>
<p>
    お名前 {{ object.last_name }} {{ object.first_name }}
</p>
<p>
    予約日時 {{ object.reservation_date|date:"Y/n/d" }} 
    {{ time }}
</p>
<p>
    予約人数 {{ object.reservation_count }}
</p>
<p>
    電話番号 {{ object.tell }}
</p>
<p>
    お祝い {{ celebration_existence }}
</p>
<p>
    お店への要望 {{ object.demand }}
</p>
<button>
    <a href="{% url 'reservations:reservationDetail' pk=object.id %}">
    戻る
    </a>
</button>
<form method="POST">
{% csrf_token %}
<input type="submit" value="削除" onClick="return Check()">
</form>

<script type="text/javascript">
   function Check(){
       var checked = confirm("本当に削除してよろしいでしょうか？");
       if (checked == true) {
           return true;
       } else {
           return false;
       }
   }
</script>
{% endblock %}

restaurant/templates/store/reservationDetail.html
{% extends 'base.html' %}
{% block content %}
    <h2>予約詳細</h2>
    <p>
        予約ID {{ object.id }}
    </p>
    <p>
        お名前 {{ object.last_name }} {{ object.first_name }}
    </p>
    <p>
        予約日時 {{ object.reservation_date|date:"Y/n/d" }} 
        {{ time }}
    </p>
    <p>
        予約人数 {{ object.reservation_count }}
    </p>
    <p>
        電話番号 {{ object.tell }}
    </p>
    <p>
        お祝い {{ celebration_existence }}
    </p>
    <p>
        お店への要望 {{ object.demand }}
    </p>
    <button>
        <a href="{% url 'reservations:reservationsList' %}">
        戻る
        </a>
    </button>
    <button>
        <a href="{% url 'reservations:reservationUpdate' pk=object.id %}">
        更新
        </a>
    </button>
    <button>
        <a href="{% url 'reservations:reservationDelete' pk=object.id %}">
        削除
        </a>
    </button>
{% endblock %}

restaurant/templates/store/reservationUpdate.html
{% extends 'base.html' %}
{% block content %}
<h2>予約更新</h2>
<form method='POST' novalidate>
    {% csrf_token %}
    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            【{{ error }}】
        {% endfor %}
    {% endif %}
    <p>
        予約ID {{ reservation.id }}
    <p>
        お名前 {{ form.last_name }} {{ form.first_name }}
    </p>
    <p>
        来店日時 {{ form.reservation_day}} {{ form.reservation_time }}
    </p>
    <p>
        来店人数 {{ form.reservation_count }}
    </p>
    <p>
        電話番号 {{ form.tell }}
    </p>
    <p>
        お祝い {{ form.celebration_existence }}
    </p>
    <p>
        お店への要望 {{ form.demand }}
    </P>
    <button>
        <a href="{% url 'reservations:reservationDetail' pk=reservation.id%}">
        戻る
        </a>
    </button>
    <input type='submit' value='更新'>
</form>
{% endblock %}

restaurant/templates/store/reservationsList.html
{% extends 'base.html' %}
{% block content %}
<form method='GET' action="{% url 'reservations:reservationsList' %}">
    <p>予約ID: <input type="text" name="id" value="{{ id }}"></p>
    <p>
        予約者: 
        <input type="text" name="last_name" value="{{ last_name }}"> <input type='text' name='first_name' value="{{ first_name }}">
    </p>
    <p>
        予約日:
        <input type="date" name ="start_day" value="{{ start_day }}"> 
        <input type="date" name="end_day" value="{{ end_day }}">
    </p>
    <p>
        予約人数: 
        <select name='reservation_count'>
            <option value="{{ reservation_count }}">{{ reservation_count }}</option>
            <option value=></option>
            <option value=1>1</option>
            <option value=2>2</option>
            <option value=3>3</option>
            <option value=4>4</option>
            <option value=5>5</option>
            <option value=6>6</option>
        </select>
    </p>
    <p>電話番号: <input type="text" name="tell" value="{{ tell }}"></p>
    <p>予約受付日: <input type="date" name="created_at" value="{{ created_at }}"></p>
    <p><input type="submit" value="検索"></p>
</form>
<table>
    <tr>
        <th>予約ID</th>
        <th>予約者</th>
        <th>予約日</th>
        <th>予約時間</th>
        <th>予約人数</th>
        <th>予約受付日</th>
        <th>電話番号</th>
    </tr>
    {% for object in object_list %}
    <tr>
        <td>
            <a href="{% url 'reservations:reservationDetail' object.id %}">
                {{ object.id }}
            </a>
        </td>
        <td>{{ object.last_name}} {{ object.first_name }}</td>
        <td>{{ object.reservation_date|date:"Y/n/d" }}</td>
        <td>{{ object.reservation_date|date:"H:i" }}</td>
        <td>{{ object.reservation_count }}人</td>
        <td>{{ object.created_at|date:"Y/n/d" }}</td>
        <td>{{ object.tell }}</td>
    </tr>
    {% endfor %}
</table>
{% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">前へ</span>
                </a>
                </li>
        
                <!-- 「前へ」と「次へ」の間の装飾文字 -->
                {% comment %} <li class="page-item">
                <span class="sr-only">..........</span>
                </li> {% endcomment %}
            {% endif %}
        
        
            {% for num in paginator.page_range %}
                {% if num <= page_obj.number|add:2 and num >= page_obj.number|add:-2 %}
                    {% if page_obj.number == num %}
                        <li class="page-item active">
                        <span class="page-link">
                        {{ num }}
                        <span class="sr-only">⇦</span>
                        </span>
                        </li>
                    {% else %}
                        <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
        
            {% if page_obj.has_next %}
                <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" pagearia-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">次へ</span>
                </a>
                </li>
            {% endif %}
        
            <li class="p-md-2">
            {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </li>
        </ul>
    </nav>
{% endif %}
{% endblock %}