restaurant/reservations/urls.py
from django.urls import path
from . import views
from .views import (
    ReservationDeleteView, ReservationsListView, ReservationDetailView
)

app_name = 'reservations'

urlpatterns = [
    path('reservation', views.ReservationView, name='reservation'),
    path('reservationsList', ReservationsListView.as_view(), name='reservationsList'),
    path('reservationDetail/<int:pk>', ReservationDetailView.as_view(), name='reservationDetail'),
    path('reservationUpdate/<int:pk>', views.ReservationUpdateView, name='reservationUpdate'),
    path('reservationDelete/<int:pk>', ReservationDeleteView.as_view(), name='reservationDelete'),

    
]

restaurant/restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('reservations.urls')),
    path('users/', include('users.urls')),
]

restaurant/users/urls.py
from django.urls import path
from .views import AdminLogoutView, HomeView, AdminLoginView 

app_name = 'users'

urlpatterns = [
    path('home', HomeView.as_view(), name='home'),
    path('admin_login', AdminLoginView.as_view(), name='admin_login'),
    path('admin_logout', AdminLogoutView.as_view(), name='admin_logout')
]

restaurant/templates/admin_login.html
{% block content %}
<h2>ログイン</h2>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="ログイン">
</form>

<a href="{% url 'users:home' %}">
    トップページへ
</a>

{% endblock %}

restaurant/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
    </head>
    <body>
        {% if user.is_authenticated %}
            <a href="{% url 'users:admin_logout' %}">ログアウト</a>
        {% endif %}
        {% block content %}
        {% endblock %}
    </body>
</html

restaurant/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>top page</h1>
<a href="{% url 'reservations:reservation' %}">
    予約ページへ
</a>
<a href="{% url 'users:admin_login' %}">
    管理者画面
</a>
{% endblock %}